// default package
// Generated Nov 26, 2019 1:10:25 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Kids generated by hbm2java
 */
public class Kids implements java.io.Serializable {

	private int kidsid;
	private User user;
	private String kidsname;
	private Set<KidsFamily> kidsFamilies = new HashSet<KidsFamily>(0);
	private Set<KidsFamilytv> kidsFamilytvs = new HashSet<KidsFamilytv>(0);
	private Set<Aoks> aokses = new HashSet<Aoks>(0);

	public Kids() {
	}

	public Kids(int kidsid) {
		this.kidsid = kidsid;
	}

	public Kids(int kidsid, User user, String kidsname, Set<KidsFamily> kidsFamilies, Set<KidsFamilytv> kidsFamilytvs,
			Set<Aoks> aokses) {
		this.kidsid = kidsid;
		this.user = user;
		this.kidsname = kidsname;
		this.kidsFamilies = kidsFamilies;
		this.kidsFamilytvs = kidsFamilytvs;
		this.aokses = aokses;
	}

	public int getKidsid() {
		return this.kidsid;
	}

	public void setKidsid(int kidsid) {
		this.kidsid = kidsid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getKidsname() {
		return this.kidsname;
	}

	public void setKidsname(String kidsname) {
		this.kidsname = kidsname;
	}

	public Set<KidsFamily> getKidsFamilies() {
		return this.kidsFamilies;
	}

	public void setKidsFamilies(Set<KidsFamily> kidsFamilies) {
		this.kidsFamilies = kidsFamilies;
	}

	public Set<KidsFamilytv> getKidsFamilytvs() {
		return this.kidsFamilytvs;
	}

	public void setKidsFamilytvs(Set<KidsFamilytv> kidsFamilytvs) {
		this.kidsFamilytvs = kidsFamilytvs;
	}

	public Set<Aoks> getAokses() {
		return this.aokses;
	}

	public void setAokses(Set<Aoks> aokses) {
		this.aokses = aokses;
	}

}
