// default package
// Generated Nov 26, 2019 1:10:25 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * KidsFamilytv generated by hbm2java
 */
public class KidsFamilytv implements java.io.Serializable {

	private int kidsFamilytvid;
	private Kids kids;
	private Home home;
	private String kidsFamilytvname;
	private Set<KidsFamilytvdetail> kidsFamilytvdetails = new HashSet<KidsFamilytvdetail>(0);

	public KidsFamilytv() {
	}

	public KidsFamilytv(int kidsFamilytvid) {
		this.kidsFamilytvid = kidsFamilytvid;
	}

	public KidsFamilytv(int kidsFamilytvid, Kids kids, Home home, String kidsFamilytvname,
			Set<KidsFamilytvdetail> kidsFamilytvdetails) {
		this.kidsFamilytvid = kidsFamilytvid;
		this.kids = kids;
		this.home = home;
		this.kidsFamilytvname = kidsFamilytvname;
		this.kidsFamilytvdetails = kidsFamilytvdetails;
	}

	public int getKidsFamilytvid() {
		return this.kidsFamilytvid;
	}

	public void setKidsFamilytvid(int kidsFamilytvid) {
		this.kidsFamilytvid = kidsFamilytvid;
	}

	public Kids getKids() {
		return this.kids;
	}

	public void setKids(Kids kids) {
		this.kids = kids;
	}

	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	public String getKidsFamilytvname() {
		return this.kidsFamilytvname;
	}

	public void setKidsFamilytvname(String kidsFamilytvname) {
		this.kidsFamilytvname = kidsFamilytvname;
	}

	public Set<KidsFamilytvdetail> getKidsFamilytvdetails() {
		return this.kidsFamilytvdetails;
	}

	public void setKidsFamilytvdetails(Set<KidsFamilytvdetail> kidsFamilytvdetails) {
		this.kidsFamilytvdetails = kidsFamilytvdetails;
	}

}
