// default package
// Generated Nov 26, 2019 1:10:25 PM by Hibernate Tools 4.0.1.Final

/**
 * KidsFamilytvdetail generated by hbm2java
 */
public class KidsFamilytvdetail implements java.io.Serializable {

	private int kidsFamilyTvdetailid;
	private KidsFamilytv kidsFamilytv;
	private String kidsFamilyTvdetailname;

	public KidsFamilytvdetail() {
	}

	public KidsFamilytvdetail(int kidsFamilyTvdetailid) {
		this.kidsFamilyTvdetailid = kidsFamilyTvdetailid;
	}

	public KidsFamilytvdetail(int kidsFamilyTvdetailid, KidsFamilytv kidsFamilytv, String kidsFamilyTvdetailname) {
		this.kidsFamilyTvdetailid = kidsFamilyTvdetailid;
		this.kidsFamilytv = kidsFamilytv;
		this.kidsFamilyTvdetailname = kidsFamilyTvdetailname;
	}

	public int getKidsFamilyTvdetailid() {
		return this.kidsFamilyTvdetailid;
	}

	public void setKidsFamilyTvdetailid(int kidsFamilyTvdetailid) {
		this.kidsFamilyTvdetailid = kidsFamilyTvdetailid;
	}

	public KidsFamilytv getKidsFamilytv() {
		return this.kidsFamilytv;
	}

	public void setKidsFamilytv(KidsFamilytv kidsFamilytv) {
		this.kidsFamilytv = kidsFamilytv;
	}

	public String getKidsFamilyTvdetailname() {
		return this.kidsFamilyTvdetailname;
	}

	public void setKidsFamilyTvdetailname(String kidsFamilyTvdetailname) {
		this.kidsFamilyTvdetailname = kidsFamilyTvdetailname;
	}

}
