// default package
// Generated Nov 26, 2019 1:10:25 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Throwback generated by hbm2java
 */
public class Throwback implements java.io.Serializable {

	private int throwbackTvid;
	private TvShows tvShows;
	private Home home;
	private String throwbackTvname;
	private Set<Throwbacktvdetail> throwbacktvdetails = new HashSet<Throwbacktvdetail>(0);

	public Throwback() {
	}

	public Throwback(int throwbackTvid) {
		this.throwbackTvid = throwbackTvid;
	}

	public Throwback(int throwbackTvid, TvShows tvShows, Home home, String throwbackTvname,
			Set<Throwbacktvdetail> throwbacktvdetails) {
		this.throwbackTvid = throwbackTvid;
		this.tvShows = tvShows;
		this.home = home;
		this.throwbackTvname = throwbackTvname;
		this.throwbacktvdetails = throwbacktvdetails;
	}

	public int getThrowbackTvid() {
		return this.throwbackTvid;
	}

	public void setThrowbackTvid(int throwbackTvid) {
		this.throwbackTvid = throwbackTvid;
	}

	public TvShows getTvShows() {
		return this.tvShows;
	}

	public void setTvShows(TvShows tvShows) {
		this.tvShows = tvShows;
	}

	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	public String getThrowbackTvname() {
		return this.throwbackTvname;
	}

	public void setThrowbackTvname(String throwbackTvname) {
		this.throwbackTvname = throwbackTvname;
	}

	public Set<Throwbacktvdetail> getThrowbacktvdetails() {
		return this.throwbacktvdetails;
	}

	public void setThrowbacktvdetails(Set<Throwbacktvdetail> throwbacktvdetails) {
		this.throwbacktvdetails = throwbacktvdetails;
	}

}
