// default package
// Generated Nov 26, 2019 1:10:25 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Treanding generated by hbm2java
 */
public class Treanding implements java.io.Serializable {

	private int treandingtvid;
	private TvShows tvShows;
	private Home home;
	private String treandingtvname;
	private Set<Treandingtvdetail> treandingtvdetails = new HashSet<Treandingtvdetail>(0);

	public Treanding() {
	}

	public Treanding(int treandingtvid) {
		this.treandingtvid = treandingtvid;
	}

	public Treanding(int treandingtvid, TvShows tvShows, Home home, String treandingtvname,
			Set<Treandingtvdetail> treandingtvdetails) {
		this.treandingtvid = treandingtvid;
		this.tvShows = tvShows;
		this.home = home;
		this.treandingtvname = treandingtvname;
		this.treandingtvdetails = treandingtvdetails;
	}

	public int getTreandingtvid() {
		return this.treandingtvid;
	}

	public void setTreandingtvid(int treandingtvid) {
		this.treandingtvid = treandingtvid;
	}

	public TvShows getTvShows() {
		return this.tvShows;
	}

	public void setTvShows(TvShows tvShows) {
		this.tvShows = tvShows;
	}

	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	public String getTreandingtvname() {
		return this.treandingtvname;
	}

	public void setTreandingtvname(String treandingtvname) {
		this.treandingtvname = treandingtvname;
	}

	public Set<Treandingtvdetail> getTreandingtvdetails() {
		return this.treandingtvdetails;
	}

	public void setTreandingtvdetails(Set<Treandingtvdetail> treandingtvdetails) {
		this.treandingtvdetails = treandingtvdetails;
	}

}
