package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Accountsetting generated by hbm2java
 */
@Entity
@Table(name = "accountsetting", catalog = "amazoneprime")
public class Accountsetting implements java.io.Serializable {

	private int accountsettingid;
	private User user;
	private String accountSettingname;
	private Set watchhistories = new HashSet(0);
	private Set youdevices = new HashSet(0);
	private Set parentalcontrols = new HashSet(0);
	private Set languages = new HashSet(0);
	private Set subtitles = new HashSet(0);
	private Set playbacks = new HashSet(0);
	private Set youaccounts = new HashSet(0);

	public Accountsetting() {
	}

	public Accountsetting(int accountsettingid) {
		this.accountsettingid = accountsettingid;
	}

	public Accountsetting(int accountsettingid, User user, String accountSettingname, Set watchhistories,
			Set youdevices, Set parentalcontrols, Set languages, Set subtitles, Set playbacks, Set youaccounts) {
		this.accountsettingid = accountsettingid;
		this.user = user;
		this.accountSettingname = accountSettingname;
		this.watchhistories = watchhistories;
		this.youdevices = youdevices;
		this.parentalcontrols = parentalcontrols;
		this.languages = languages;
		this.subtitles = subtitles;
		this.playbacks = playbacks;
		this.youaccounts = youaccounts;
	}

	@Id

	@Column(name = "accountsettingid", unique = true, nullable = false)
	public int getAccountsettingid() {
		return this.accountsettingid;
	}

	public void setAccountsettingid(int accountsettingid) {
		this.accountsettingid = accountsettingid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid_fk")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "accountSettingname")
	public String getAccountSettingname() {
		return this.accountSettingname;
	}

	public void setAccountSettingname(String accountSettingname) {
		this.accountSettingname = accountSettingname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountsetting")
	public Set getWatchhistories() {
		return this.watchhistories;
	}

	public void setWatchhistories(Set watchhistories) {
		this.watchhistories = watchhistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountsetting")
	public Set getYoudevices() {
		return this.youdevices;
	}

	public void setYoudevices(Set youdevices) {
		this.youdevices = youdevices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountsetting")
	public Set getParentalcontrols() {
		return this.parentalcontrols;
	}

	public void setParentalcontrols(Set parentalcontrols) {
		this.parentalcontrols = parentalcontrols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountsetting")
	public Set getLanguages() {
		return this.languages;
	}

	public void setLanguages(Set languages) {
		this.languages = languages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountsetting")
	public Set getSubtitles() {
		return this.subtitles;
	}

	public void setSubtitles(Set subtitles) {
		this.subtitles = subtitles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountsetting")
	public Set getPlaybacks() {
		return this.playbacks;
	}

	public void setPlaybacks(Set playbacks) {
		this.playbacks = playbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountsetting")
	public Set getYouaccounts() {
		return this.youaccounts;
	}

	public void setYouaccounts(Set youaccounts) {
		this.youaccounts = youaccounts;
	}

}
