package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActionAdventuretvdetail generated by hbm2java
 */
@Entity
@Table(name = "action_adventuretvdetail", catalog = "amazoneprime")
public class ActionAdventuretvdetail implements java.io.Serializable {

	private int actionAdventureTvdetailid;
	private Actionadventure actionadventure;
	private String actionAdventureTvdetailname;

	public ActionAdventuretvdetail() {
	}

	public ActionAdventuretvdetail(int actionAdventureTvdetailid) {
		this.actionAdventureTvdetailid = actionAdventureTvdetailid;
	}

	public ActionAdventuretvdetail(int actionAdventureTvdetailid, Actionadventure actionadventure,
			String actionAdventureTvdetailname) {
		this.actionAdventureTvdetailid = actionAdventureTvdetailid;
		this.actionadventure = actionadventure;
		this.actionAdventureTvdetailname = actionAdventureTvdetailname;
	}

	@Id

	@Column(name = "action_adventureTVDetailid", unique = true, nullable = false)
	public int getActionAdventureTvdetailid() {
		return this.actionAdventureTvdetailid;
	}

	public void setActionAdventureTvdetailid(int actionAdventureTvdetailid) {
		this.actionAdventureTvdetailid = actionAdventureTvdetailid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "actionAdventureid_fk")
	public Actionadventure getActionadventure() {
		return this.actionadventure;
	}

	public void setActionadventure(Actionadventure actionadventure) {
		this.actionadventure = actionadventure;
	}

	@Column(name = "action_adventureTVDetailname")
	public String getActionAdventureTvdetailname() {
		return this.actionAdventureTvdetailname;
	}

	public void setActionAdventureTvdetailname(String actionAdventureTvdetailname) {
		this.actionAdventureTvdetailname = actionAdventureTvdetailname;
	}

}
