package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actionadventure generated by hbm2java
 */
@Entity
@Table(name = "actionadventure", catalog = "amazoneprime")
public class Actionadventure implements java.io.Serializable {

	private int actionAdventureid;
	private Home home;
	private TvShows tvShows;
	private String actionAdventurename;
	private Set actionAdventuretvdetails = new HashSet(0);

	public Actionadventure() {
	}

	public Actionadventure(int actionAdventureid) {
		this.actionAdventureid = actionAdventureid;
	}

	public Actionadventure(int actionAdventureid, Home home, TvShows tvShows, String actionAdventurename,
			Set actionAdventuretvdetails) {
		this.actionAdventureid = actionAdventureid;
		this.home = home;
		this.tvShows = tvShows;
		this.actionAdventurename = actionAdventurename;
		this.actionAdventuretvdetails = actionAdventuretvdetails;
	}

	@Id

	@Column(name = "actionAdventureid", unique = true, nullable = false)
	public int getActionAdventureid() {
		return this.actionAdventureid;
	}

	public void setActionAdventureid(int actionAdventureid) {
		this.actionAdventureid = actionAdventureid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeid_fk")
	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tvshowid_fk")
	public TvShows getTvShows() {
		return this.tvShows;
	}

	public void setTvShows(TvShows tvShows) {
		this.tvShows = tvShows;
	}

	@Column(name = "actionAdventurename")
	public String getActionAdventurename() {
		return this.actionAdventurename;
	}

	public void setActionAdventurename(String actionAdventurename) {
		this.actionAdventurename = actionAdventurename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actionadventure")
	public Set getActionAdventuretvdetails() {
		return this.actionAdventuretvdetails;
	}

	public void setActionAdventuretvdetails(Set actionAdventuretvdetails) {
		this.actionAdventuretvdetails = actionAdventuretvdetails;
	}

}
