package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Amazoneseriesdetail generated by hbm2java
 */
@Entity
@Table(name = "amazoneseriesdetail", catalog = "amazoneprime")
public class Amazoneseriesdetail implements java.io.Serializable {

	private int amazoneSeriesid;
	private Aoks aoks;
	private String amazoneSeriesname;

	public Amazoneseriesdetail() {
	}

	public Amazoneseriesdetail(int amazoneSeriesid) {
		this.amazoneSeriesid = amazoneSeriesid;
	}

	public Amazoneseriesdetail(int amazoneSeriesid, Aoks aoks, String amazoneSeriesname) {
		this.amazoneSeriesid = amazoneSeriesid;
		this.aoks = aoks;
		this.amazoneSeriesname = amazoneSeriesname;
	}

	@Id

	@Column(name = "amazoneSeriesid", unique = true, nullable = false)
	public int getAmazoneSeriesid() {
		return this.amazoneSeriesid;
	}

	public void setAmazoneSeriesid(int amazoneSeriesid) {
		this.amazoneSeriesid = amazoneSeriesid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aoksid_fk")
	public Aoks getAoks() {
		return this.aoks;
	}

	public void setAoks(Aoks aoks) {
		this.aoks = aoks;
	}

	@Column(name = "amazoneSeriesname")
	public String getAmazoneSeriesname() {
		return this.amazoneSeriesname;
	}

	public void setAmazoneSeriesname(String amazoneSeriesname) {
		this.amazoneSeriesname = amazoneSeriesname;
	}

}
