package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Aoks generated by hbm2java
 */
@Entity
@Table(name = "aoks", catalog = "amazoneprime")
public class Aoks implements java.io.Serializable {

	private int aoksid;
	private Home home;
	private Kids kids;
	private String aoksname;
	private Set amazoneseriesdetails = new HashSet(0);

	public Aoks() {
	}

	public Aoks(int aoksid) {
		this.aoksid = aoksid;
	}

	public Aoks(int aoksid, Home home, Kids kids, String aoksname, Set amazoneseriesdetails) {
		this.aoksid = aoksid;
		this.home = home;
		this.kids = kids;
		this.aoksname = aoksname;
		this.amazoneseriesdetails = amazoneseriesdetails;
	}

	@Id

	@Column(name = "aoksid", unique = true, nullable = false)
	public int getAoksid() {
		return this.aoksid;
	}

	public void setAoksid(int aoksid) {
		this.aoksid = aoksid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeid_fk")
	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kidsid_fk")
	public Kids getKids() {
		return this.kids;
	}

	public void setKids(Kids kids) {
		this.kids = kids;
	}

	@Column(name = "aoksname")
	public String getAoksname() {
		return this.aoksname;
	}

	public void setAoksname(String aoksname) {
		this.aoksname = aoksname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aoks")
	public Set getAmazoneseriesdetails() {
		return this.amazoneseriesdetails;
	}

	public void setAmazoneseriesdetails(Set amazoneseriesdetails) {
		this.amazoneseriesdetails = amazoneseriesdetails;
	}

}
