package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comedymovie generated by hbm2java
 */
@Entity
@Table(name = "comedymovie", catalog = "amazoneprime")
public class Comedymovie implements java.io.Serializable {

	private int comedymovieid;
	private Home home;
	private Movie movie;
	private String comedymoviename;
	private Set comedymoviedetails = new HashSet(0);

	public Comedymovie() {
	}

	public Comedymovie(int comedymovieid) {
		this.comedymovieid = comedymovieid;
	}

	public Comedymovie(int comedymovieid, Home home, Movie movie, String comedymoviename, Set comedymoviedetails) {
		this.comedymovieid = comedymovieid;
		this.home = home;
		this.movie = movie;
		this.comedymoviename = comedymoviename;
		this.comedymoviedetails = comedymoviedetails;
	}

	@Id

	@Column(name = "comedymovieid", unique = true, nullable = false)
	public int getComedymovieid() {
		return this.comedymovieid;
	}

	public void setComedymovieid(int comedymovieid) {
		this.comedymovieid = comedymovieid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeid_fk")
	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "moviesid_fk")
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@Column(name = "comedymoviename")
	public String getComedymoviename() {
		return this.comedymoviename;
	}

	public void setComedymoviename(String comedymoviename) {
		this.comedymoviename = comedymoviename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comedymovie")
	public Set getComedymoviedetails() {
		return this.comedymoviedetails;
	}

	public void setComedymoviedetails(Set comedymoviedetails) {
		this.comedymoviedetails = comedymoviedetails;
	}

}
