package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Home generated by hbm2java
 */
@Entity
@Table(name = "home", catalog = "amazoneprime")
public class Home implements java.io.Serializable {

	private int homeid;
	private User user;
	private String homename;
	private Set kidsFamilies = new HashSet(0);
	private Set dramamovies = new HashSet(0);
	private Set throwbacks = new HashSet(0);
	private Set actionadventures = new HashSet(0);
	private Set comedymovies = new HashSet(0);
	private Set aokses = new HashSet(0);
	private Set treandings = new HashSet(0);
	private Set thrillermovies = new HashSet(0);
	private Set kidsFamilytvs = new HashSet(0);

	public Home() {
	}

	public Home(int homeid) {
		this.homeid = homeid;
	}

	public Home(int homeid, User user, String homename, Set kidsFamilies, Set dramamovies, Set throwbacks,
			Set actionadventures, Set comedymovies, Set aokses, Set treandings, Set thrillermovies, Set kidsFamilytvs) {
		this.homeid = homeid;
		this.user = user;
		this.homename = homename;
		this.kidsFamilies = kidsFamilies;
		this.dramamovies = dramamovies;
		this.throwbacks = throwbacks;
		this.actionadventures = actionadventures;
		this.comedymovies = comedymovies;
		this.aokses = aokses;
		this.treandings = treandings;
		this.thrillermovies = thrillermovies;
		this.kidsFamilytvs = kidsFamilytvs;
	}

	@Id

	@Column(name = "homeid", unique = true, nullable = false)
	public int getHomeid() {
		return this.homeid;
	}

	public void setHomeid(int homeid) {
		this.homeid = homeid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid_fk")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "homename")
	public String getHomename() {
		return this.homename;
	}

	public void setHomename(String homename) {
		this.homename = homename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "home")
	public Set getKidsFamilies() {
		return this.kidsFamilies;
	}

	public void setKidsFamilies(Set kidsFamilies) {
		this.kidsFamilies = kidsFamilies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "home")
	public Set getDramamovies() {
		return this.dramamovies;
	}

	public void setDramamovies(Set dramamovies) {
		this.dramamovies = dramamovies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "home")
	public Set getThrowbacks() {
		return this.throwbacks;
	}

	public void setThrowbacks(Set throwbacks) {
		this.throwbacks = throwbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "home")
	public Set getActionadventures() {
		return this.actionadventures;
	}

	public void setActionadventures(Set actionadventures) {
		this.actionadventures = actionadventures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "home")
	public Set getComedymovies() {
		return this.comedymovies;
	}

	public void setComedymovies(Set comedymovies) {
		this.comedymovies = comedymovies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "home")
	public Set getAokses() {
		return this.aokses;
	}

	public void setAokses(Set aokses) {
		this.aokses = aokses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "home")
	public Set getTreandings() {
		return this.treandings;
	}

	public void setTreandings(Set treandings) {
		this.treandings = treandings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "home")
	public Set getThrillermovies() {
		return this.thrillermovies;
	}

	public void setThrillermovies(Set thrillermovies) {
		this.thrillermovies = thrillermovies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "home")
	public Set getKidsFamilytvs() {
		return this.kidsFamilytvs;
	}

	public void setKidsFamilytvs(Set kidsFamilytvs) {
		this.kidsFamilytvs = kidsFamilytvs;
	}

}
