package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KidsFamily generated by hbm2java
 */
@Entity
@Table(name = "kids_family", catalog = "amazoneprime")
public class KidsFamily implements java.io.Serializable {

	private int kidsFamilyMovieid;
	private Home home;
	private Kids kids;
	private String kidsFamilyMoviename;
	private Set kidsfamilymoviedetails = new HashSet(0);

	public KidsFamily() {
	}

	public KidsFamily(int kidsFamilyMovieid) {
		this.kidsFamilyMovieid = kidsFamilyMovieid;
	}

	public KidsFamily(int kidsFamilyMovieid, Home home, Kids kids, String kidsFamilyMoviename,
			Set kidsfamilymoviedetails) {
		this.kidsFamilyMovieid = kidsFamilyMovieid;
		this.home = home;
		this.kids = kids;
		this.kidsFamilyMoviename = kidsFamilyMoviename;
		this.kidsfamilymoviedetails = kidsfamilymoviedetails;
	}

	@Id

	@Column(name = "kids_familyMovieid", unique = true, nullable = false)
	public int getKidsFamilyMovieid() {
		return this.kidsFamilyMovieid;
	}

	public void setKidsFamilyMovieid(int kidsFamilyMovieid) {
		this.kidsFamilyMovieid = kidsFamilyMovieid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeid_fk")
	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kidsid_fk")
	public Kids getKids() {
		return this.kids;
	}

	public void setKids(Kids kids) {
		this.kids = kids;
	}

	@Column(name = "kids_familyMoviename")
	public String getKidsFamilyMoviename() {
		return this.kidsFamilyMoviename;
	}

	public void setKidsFamilyMoviename(String kidsFamilyMoviename) {
		this.kidsFamilyMoviename = kidsFamilyMoviename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kidsFamily")
	public Set getKidsfamilymoviedetails() {
		return this.kidsfamilymoviedetails;
	}

	public void setKidsfamilymoviedetails(Set kidsfamilymoviedetails) {
		this.kidsfamilymoviedetails = kidsfamilymoviedetails;
	}

}
