package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language", catalog = "amazoneprime")
public class Language implements java.io.Serializable {

	private int languageid;
	private Accountsetting accountsetting;
	private String languragename;
	private Set weblanguages = new HashSet(0);

	public Language() {
	}

	public Language(int languageid) {
		this.languageid = languageid;
	}

	public Language(int languageid, Accountsetting accountsetting, String languragename, Set weblanguages) {
		this.languageid = languageid;
		this.accountsetting = accountsetting;
		this.languragename = languragename;
		this.weblanguages = weblanguages;
	}

	@Id

	@Column(name = "languageid", unique = true, nullable = false)
	public int getLanguageid() {
		return this.languageid;
	}

	public void setLanguageid(int languageid) {
		this.languageid = languageid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountsettingid_fk")
	public Accountsetting getAccountsetting() {
		return this.accountsetting;
	}

	public void setAccountsetting(Accountsetting accountsetting) {
		this.accountsetting = accountsetting;
	}

	@Column(name = "languragename")
	public String getLanguragename() {
		return this.languragename;
	}

	public void setLanguragename(String languragename) {
		this.languragename = languragename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set getWeblanguages() {
		return this.weblanguages;
	}

	public void setWeblanguages(Set weblanguages) {
		this.weblanguages = weblanguages;
	}

}
