package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prime generated by hbm2java
 */
@Entity
@Table(name = "prime", catalog = "amazoneprime")
public class Prime implements java.io.Serializable {

	private int primeid;
	private Youaccount youaccount;
	private String primename;

	public Prime() {
	}

	public Prime(int primeid) {
		this.primeid = primeid;
	}

	public Prime(int primeid, Youaccount youaccount, String primename) {
		this.primeid = primeid;
		this.youaccount = youaccount;
		this.primename = primename;
	}

	@Id

	@Column(name = "primeid", unique = true, nullable = false)
	public int getPrimeid() {
		return this.primeid;
	}

	public void setPrimeid(int primeid) {
		this.primeid = primeid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "youaccount_fk1")
	public Youaccount getYouaccount() {
		return this.youaccount;
	}

	public void setYouaccount(Youaccount youaccount) {
		this.youaccount = youaccount;
	}

	@Column(name = "primename")
	public String getPrimename() {
		return this.primename;
	}

	public void setPrimename(String primename) {
		this.primename = primename;
	}

}
