package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subtitle generated by hbm2java
 */
@Entity
@Table(name = "subtitle", catalog = "amazoneprime")
public class Subtitle implements java.io.Serializable {

	private int subtitleid;
	private Accountsetting accountsetting;
	private String subtitlename;
	private Set subtitledetails = new HashSet(0);

	public Subtitle() {
	}

	public Subtitle(int subtitleid) {
		this.subtitleid = subtitleid;
	}

	public Subtitle(int subtitleid, Accountsetting accountsetting, String subtitlename, Set subtitledetails) {
		this.subtitleid = subtitleid;
		this.accountsetting = accountsetting;
		this.subtitlename = subtitlename;
		this.subtitledetails = subtitledetails;
	}

	@Id

	@Column(name = "subtitleid", unique = true, nullable = false)
	public int getSubtitleid() {
		return this.subtitleid;
	}

	public void setSubtitleid(int subtitleid) {
		this.subtitleid = subtitleid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountsettingid_fk")
	public Accountsetting getAccountsetting() {
		return this.accountsetting;
	}

	public void setAccountsetting(Accountsetting accountsetting) {
		this.accountsetting = accountsetting;
	}

	@Column(name = "subtitlename")
	public String getSubtitlename() {
		return this.subtitlename;
	}

	public void setSubtitlename(String subtitlename) {
		this.subtitlename = subtitlename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subtitle")
	public Set getSubtitledetails() {
		return this.subtitledetails;
	}

	public void setSubtitledetails(Set subtitledetails) {
		this.subtitledetails = subtitledetails;
	}

}
