package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Thrillermoviedetail generated by hbm2java
 */
@Entity
@Table(name = "thrillermoviedetail", catalog = "amazoneprime")
public class Thrillermoviedetail implements java.io.Serializable {

	private int thrillermoviedetailid;
	private Thrillermovie thrillermovie;
	private String thrillermoviedetailname;

	public Thrillermoviedetail() {
	}

	public Thrillermoviedetail(int thrillermoviedetailid) {
		this.thrillermoviedetailid = thrillermoviedetailid;
	}

	public Thrillermoviedetail(int thrillermoviedetailid, Thrillermovie thrillermovie, String thrillermoviedetailname) {
		this.thrillermoviedetailid = thrillermoviedetailid;
		this.thrillermovie = thrillermovie;
		this.thrillermoviedetailname = thrillermoviedetailname;
	}

	@Id

	@Column(name = "thrillermoviedetailid", unique = true, nullable = false)
	public int getThrillermoviedetailid() {
		return this.thrillermoviedetailid;
	}

	public void setThrillermoviedetailid(int thrillermoviedetailid) {
		this.thrillermoviedetailid = thrillermoviedetailid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "thrillermovieid_fk")
	public Thrillermovie getThrillermovie() {
		return this.thrillermovie;
	}

	public void setThrillermovie(Thrillermovie thrillermovie) {
		this.thrillermovie = thrillermovie;
	}

	@Column(name = "thrillermoviedetailname")
	public String getThrillermoviedetailname() {
		return this.thrillermoviedetailname;
	}

	public void setThrillermoviedetailname(String thrillermoviedetailname) {
		this.thrillermoviedetailname = thrillermoviedetailname;
	}

}
