package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Throwback generated by hbm2java
 */
@Entity
@Table(name = "throwback", catalog = "amazoneprime")
public class Throwback implements java.io.Serializable {

	private int throwbackTvid;
	private Home home;
	private TvShows tvShows;
	private String throwbackTvname;
	private Set throwbacktvdetails = new HashSet(0);

	public Throwback() {
	}

	public Throwback(int throwbackTvid) {
		this.throwbackTvid = throwbackTvid;
	}

	public Throwback(int throwbackTvid, Home home, TvShows tvShows, String throwbackTvname, Set throwbacktvdetails) {
		this.throwbackTvid = throwbackTvid;
		this.home = home;
		this.tvShows = tvShows;
		this.throwbackTvname = throwbackTvname;
		this.throwbacktvdetails = throwbacktvdetails;
	}

	@Id

	@Column(name = "throwbackTVid", unique = true, nullable = false)
	public int getThrowbackTvid() {
		return this.throwbackTvid;
	}

	public void setThrowbackTvid(int throwbackTvid) {
		this.throwbackTvid = throwbackTvid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeid_fk")
	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tvshowid_fk")
	public TvShows getTvShows() {
		return this.tvShows;
	}

	public void setTvShows(TvShows tvShows) {
		this.tvShows = tvShows;
	}

	@Column(name = "throwbackTVname")
	public String getThrowbackTvname() {
		return this.throwbackTvname;
	}

	public void setThrowbackTvname(String throwbackTvname) {
		this.throwbackTvname = throwbackTvname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "throwback")
	public Set getThrowbacktvdetails() {
		return this.throwbacktvdetails;
	}

	public void setThrowbacktvdetails(Set throwbacktvdetails) {
		this.throwbacktvdetails = throwbacktvdetails;
	}

}
