package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Watchhistorydetail generated by hbm2java
 */
@Entity
@Table(name = "watchhistorydetail", catalog = "amazoneprime")
public class Watchhistorydetail implements java.io.Serializable {

	private int watchhistorydetailid;
	private Watchhistory watchhistory;
	private String watchhistorydetailname;

	public Watchhistorydetail() {
	}

	public Watchhistorydetail(int watchhistorydetailid) {
		this.watchhistorydetailid = watchhistorydetailid;
	}

	public Watchhistorydetail(int watchhistorydetailid, Watchhistory watchhistory, String watchhistorydetailname) {
		this.watchhistorydetailid = watchhistorydetailid;
		this.watchhistory = watchhistory;
		this.watchhistorydetailname = watchhistorydetailname;
	}

	@Id

	@Column(name = "watchhistorydetailid", unique = true, nullable = false)
	public int getWatchhistorydetailid() {
		return this.watchhistorydetailid;
	}

	public void setWatchhistorydetailid(int watchhistorydetailid) {
		this.watchhistorydetailid = watchhistorydetailid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "watchhistoryid_fk")
	public Watchhistory getWatchhistory() {
		return this.watchhistory;
	}

	public void setWatchhistory(Watchhistory watchhistory) {
		this.watchhistory = watchhistory;
	}

	@Column(name = "watchhistorydetailname")
	public String getWatchhistorydetailname() {
		return this.watchhistorydetailname;
	}

	public void setWatchhistorydetailname(String watchhistorydetailname) {
		this.watchhistorydetailname = watchhistorydetailname;
	}

}
