package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Youaccount generated by hbm2java
 */
@Entity
@Table(name = "youaccount", catalog = "amazoneprime")
public class Youaccount implements java.io.Serializable {

	private int youacountid;
	private Accountsetting accountsetting;
	private String youaccountname;
	private Set youdetails = new HashSet(0);
	private Set youpaymenthistories = new HashSet(0);
	private Set primes = new HashSet(0);

	public Youaccount() {
	}

	public Youaccount(int youacountid) {
		this.youacountid = youacountid;
	}

	public Youaccount(int youacountid, Accountsetting accountsetting, String youaccountname, Set youdetails,
			Set youpaymenthistories, Set primes) {
		this.youacountid = youacountid;
		this.accountsetting = accountsetting;
		this.youaccountname = youaccountname;
		this.youdetails = youdetails;
		this.youpaymenthistories = youpaymenthistories;
		this.primes = primes;
	}

	@Id

	@Column(name = "youacountid", unique = true, nullable = false)
	public int getYouacountid() {
		return this.youacountid;
	}

	public void setYouacountid(int youacountid) {
		this.youacountid = youacountid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountsettingid_fk")
	public Accountsetting getAccountsetting() {
		return this.accountsetting;
	}

	public void setAccountsetting(Accountsetting accountsetting) {
		this.accountsetting = accountsetting;
	}

	@Column(name = "youaccountname")
	public String getYouaccountname() {
		return this.youaccountname;
	}

	public void setYouaccountname(String youaccountname) {
		this.youaccountname = youaccountname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "youaccount")
	public Set getYoudetails() {
		return this.youdetails;
	}

	public void setYoudetails(Set youdetails) {
		this.youdetails = youdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "youaccount")
	public Set getYoupaymenthistories() {
		return this.youpaymenthistories;
	}

	public void setYoupaymenthistories(Set youpaymenthistories) {
		this.youpaymenthistories = youpaymenthistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "youaccount")
	public Set getPrimes() {
		return this.primes;
	}

	public void setPrimes(Set primes) {
		this.primes = primes;
	}

}
