package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Youdevice generated by hbm2java
 */
@Entity
@Table(name = "youdevice", catalog = "amazoneprime")
public class Youdevice implements java.io.Serializable {

	private int yourdeviceid;
	private Accountsetting accountsetting;
	private String yourdecicename;
	private Set registerdevices = new HashSet(0);

	public Youdevice() {
	}

	public Youdevice(int yourdeviceid) {
		this.yourdeviceid = yourdeviceid;
	}

	public Youdevice(int yourdeviceid, Accountsetting accountsetting, String yourdecicename, Set registerdevices) {
		this.yourdeviceid = yourdeviceid;
		this.accountsetting = accountsetting;
		this.yourdecicename = yourdecicename;
		this.registerdevices = registerdevices;
	}

	@Id

	@Column(name = "yourdeviceid", unique = true, nullable = false)
	public int getYourdeviceid() {
		return this.yourdeviceid;
	}

	public void setYourdeviceid(int yourdeviceid) {
		this.yourdeviceid = yourdeviceid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountsettingid_fk")
	public Accountsetting getAccountsetting() {
		return this.accountsetting;
	}

	public void setAccountsetting(Accountsetting accountsetting) {
		this.accountsetting = accountsetting;
	}

	@Column(name = "yourdecicename")
	public String getYourdecicename() {
		return this.yourdecicename;
	}

	public void setYourdecicename(String yourdecicename) {
		this.yourdecicename = yourdecicename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "youdevice")
	public Set getRegisterdevices() {
		return this.registerdevices;
	}

	public void setRegisterdevices(Set registerdevices) {
		this.registerdevices = registerdevices;
	}

}
