package ddv;
// Generated Nov 26, 2019 5:43:21 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Youpaymenthistory generated by hbm2java
 */
@Entity
@Table(name = "youpaymenthistory", catalog = "amazoneprime")
public class Youpaymenthistory implements java.io.Serializable {

	private int youpaymenthistoryid;
	private Youaccount youaccount;
	private String youpaymenthistoryname;

	public Youpaymenthistory() {
	}

	public Youpaymenthistory(int youpaymenthistoryid) {
		this.youpaymenthistoryid = youpaymenthistoryid;
	}

	public Youpaymenthistory(int youpaymenthistoryid, Youaccount youaccount, String youpaymenthistoryname) {
		this.youpaymenthistoryid = youpaymenthistoryid;
		this.youaccount = youaccount;
		this.youpaymenthistoryname = youpaymenthistoryname;
	}

	@Id

	@Column(name = "youpaymenthistoryid", unique = true, nullable = false)
	public int getYoupaymenthistoryid() {
		return this.youpaymenthistoryid;
	}

	public void setYoupaymenthistoryid(int youpaymenthistoryid) {
		this.youpaymenthistoryid = youpaymenthistoryid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "youaccount_fk1")
	public Youaccount getYouaccount() {
		return this.youaccount;
	}

	public void setYouaccount(Youaccount youaccount) {
		this.youaccount = youaccount;
	}

	@Column(name = "youpaymenthistoryname")
	public String getYoupaymenthistoryname() {
		return this.youpaymenthistoryname;
	}

	public void setYoupaymenthistoryname(String youpaymenthistoryname) {
		this.youpaymenthistoryname = youpaymenthistoryname;
	}

}
