// default package
// Generated Nov 26, 2019 1:29:33 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Autoplay generated by hbm2java
 */
@Entity
@Table(name = "autoplay", catalog = "amazoneprime")
public class Autoplay implements java.io.Serializable {

	private int autoplayid;
	private Playback playback;
	private String autoplayname;

	public Autoplay() {
	}

	public Autoplay(int autoplayid) {
		this.autoplayid = autoplayid;
	}

	public Autoplay(int autoplayid, Playback playback, String autoplayname) {
		this.autoplayid = autoplayid;
		this.playback = playback;
		this.autoplayname = autoplayname;
	}

	@Id

	@Column(name = "autoplayid", unique = true, nullable = false)
	public int getAutoplayid() {
		return this.autoplayid;
	}

	public void setAutoplayid(int autoplayid) {
		this.autoplayid = autoplayid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "playbackid_fk")
	public Playback getPlayback() {
		return this.playback;
	}

	public void setPlayback(Playback playback) {
		this.playback = playback;
	}

	@Column(name = "autoplayname")
	public String getAutoplayname() {
		return this.autoplayname;
	}

	public void setAutoplayname(String autoplayname) {
		this.autoplayname = autoplayname;
	}

}
