// default package
// Generated Nov 26, 2019 1:29:33 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dramamovie generated by hbm2java
 */
@Entity
@Table(name = "dramamovie", catalog = "amazoneprime")
public class Dramamovie implements java.io.Serializable {

	private int dramamoviesid;
	private Home home;
	private Movie movie;
	private String dramamoviesname;
	private Set<Dramamoviedetail> dramamoviedetails = new HashSet<Dramamoviedetail>(0);

	public Dramamovie() {
	}

	public Dramamovie(int dramamoviesid) {
		this.dramamoviesid = dramamoviesid;
	}

	public Dramamovie(int dramamoviesid, Home home, Movie movie, String dramamoviesname,
			Set<Dramamoviedetail> dramamoviedetails) {
		this.dramamoviesid = dramamoviesid;
		this.home = home;
		this.movie = movie;
		this.dramamoviesname = dramamoviesname;
		this.dramamoviedetails = dramamoviedetails;
	}

	@Id

	@Column(name = "dramamoviesid", unique = true, nullable = false)
	public int getDramamoviesid() {
		return this.dramamoviesid;
	}

	public void setDramamoviesid(int dramamoviesid) {
		this.dramamoviesid = dramamoviesid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeid_fk")
	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "moviesid_fk")
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@Column(name = "dramamoviesname")
	public String getDramamoviesname() {
		return this.dramamoviesname;
	}

	public void setDramamoviesname(String dramamoviesname) {
		this.dramamoviesname = dramamoviesname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dramamovie")
	public Set<Dramamoviedetail> getDramamoviedetails() {
		return this.dramamoviedetails;
	}

	public void setDramamoviedetails(Set<Dramamoviedetail> dramamoviedetails) {
		this.dramamoviedetails = dramamoviedetails;
	}

}
