// default package
// Generated Nov 26, 2019 1:29:33 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KidsFamilytvdetail generated by hbm2java
 */
@Entity
@Table(name = "kids_familytvdetail", catalog = "amazoneprime")
public class KidsFamilytvdetail implements java.io.Serializable {

	private int kidsFamilyTvdetailid;
	private KidsFamilytv kidsFamilytv;
	private String kidsFamilyTvdetailname;

	public KidsFamilytvdetail() {
	}

	public KidsFamilytvdetail(int kidsFamilyTvdetailid) {
		this.kidsFamilyTvdetailid = kidsFamilyTvdetailid;
	}

	public KidsFamilytvdetail(int kidsFamilyTvdetailid, KidsFamilytv kidsFamilytv, String kidsFamilyTvdetailname) {
		this.kidsFamilyTvdetailid = kidsFamilyTvdetailid;
		this.kidsFamilytv = kidsFamilytv;
		this.kidsFamilyTvdetailname = kidsFamilyTvdetailname;
	}

	@Id

	@Column(name = "kids_familyTvdetailid", unique = true, nullable = false)
	public int getKidsFamilyTvdetailid() {
		return this.kidsFamilyTvdetailid;
	}

	public void setKidsFamilyTvdetailid(int kidsFamilyTvdetailid) {
		this.kidsFamilyTvdetailid = kidsFamilyTvdetailid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kids_familytvid_fk")
	public KidsFamilytv getKidsFamilytv() {
		return this.kidsFamilytv;
	}

	public void setKidsFamilytv(KidsFamilytv kidsFamilytv) {
		this.kidsFamilytv = kidsFamilytv;
	}

	@Column(name = "kids_familyTvdetailname")
	public String getKidsFamilyTvdetailname() {
		return this.kidsFamilyTvdetailname;
	}

	public void setKidsFamilyTvdetailname(String kidsFamilyTvdetailname) {
		this.kidsFamilyTvdetailname = kidsFamilyTvdetailname;
	}

}
