// default package
// Generated Nov 26, 2019 1:29:33 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parentalcontrol generated by hbm2java
 */
@Entity
@Table(name = "parentalcontrol", catalog = "amazoneprime")
public class Parentalcontrol implements java.io.Serializable {

	private int parentalid;
	private Accountsetting accountsetting;
	private String parentalname;
	private Set<Primevideopin> primevideopins = new HashSet<Primevideopin>(0);

	public Parentalcontrol() {
	}

	public Parentalcontrol(int parentalid) {
		this.parentalid = parentalid;
	}

	public Parentalcontrol(int parentalid, Accountsetting accountsetting, String parentalname,
			Set<Primevideopin> primevideopins) {
		this.parentalid = parentalid;
		this.accountsetting = accountsetting;
		this.parentalname = parentalname;
		this.primevideopins = primevideopins;
	}

	@Id

	@Column(name = "parentalid", unique = true, nullable = false)
	public int getParentalid() {
		return this.parentalid;
	}

	public void setParentalid(int parentalid) {
		this.parentalid = parentalid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountsettingid_fk")
	public Accountsetting getAccountsetting() {
		return this.accountsetting;
	}

	public void setAccountsetting(Accountsetting accountsetting) {
		this.accountsetting = accountsetting;
	}

	@Column(name = "parentalname")
	public String getParentalname() {
		return this.parentalname;
	}

	public void setParentalname(String parentalname) {
		this.parentalname = parentalname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentalcontrol")
	public Set<Primevideopin> getPrimevideopins() {
		return this.primevideopins;
	}

	public void setPrimevideopins(Set<Primevideopin> primevideopins) {
		this.primevideopins = primevideopins;
	}

}
