// default package
// Generated Nov 26, 2019 1:29:33 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Registerdevice generated by hbm2java
 */
@Entity
@Table(name = "registerdevice", catalog = "amazoneprime")
public class Registerdevice implements java.io.Serializable {

	private int registerid;
	private Youdevice youdevice;
	private String registername;

	public Registerdevice() {
	}

	public Registerdevice(int registerid) {
		this.registerid = registerid;
	}

	public Registerdevice(int registerid, Youdevice youdevice, String registername) {
		this.registerid = registerid;
		this.youdevice = youdevice;
		this.registername = registername;
	}

	@Id

	@Column(name = "registerid", unique = true, nullable = false)
	public int getRegisterid() {
		return this.registerid;
	}

	public void setRegisterid(int registerid) {
		this.registerid = registerid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "yourdeviceid_fk")
	public Youdevice getYoudevice() {
		return this.youdevice;
	}

	public void setYoudevice(Youdevice youdevice) {
		this.youdevice = youdevice;
	}

	@Column(name = "registername")
	public String getRegistername() {
		return this.registername;
	}

	public void setRegistername(String registername) {
		this.registername = registername;
	}

}
