// default package
// Generated Nov 26, 2019 1:29:33 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Throwback generated by hbm2java
 */
@Entity
@Table(name = "throwback", catalog = "amazoneprime")
public class Throwback implements java.io.Serializable {

	private int throwbackTvid;
	private TvShows tvShows;
	private Home home;
	private String throwbackTvname;
	private Set<Throwbacktvdetail> throwbacktvdetails = new HashSet<Throwbacktvdetail>(0);

	public Throwback() {
	}

	public Throwback(int throwbackTvid) {
		this.throwbackTvid = throwbackTvid;
	}

	public Throwback(int throwbackTvid, TvShows tvShows, Home home, String throwbackTvname,
			Set<Throwbacktvdetail> throwbacktvdetails) {
		this.throwbackTvid = throwbackTvid;
		this.tvShows = tvShows;
		this.home = home;
		this.throwbackTvname = throwbackTvname;
		this.throwbacktvdetails = throwbacktvdetails;
	}

	@Id

	@Column(name = "throwbackTVid", unique = true, nullable = false)
	public int getThrowbackTvid() {
		return this.throwbackTvid;
	}

	public void setThrowbackTvid(int throwbackTvid) {
		this.throwbackTvid = throwbackTvid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tvshowid_fk")
	public TvShows getTvShows() {
		return this.tvShows;
	}

	public void setTvShows(TvShows tvShows) {
		this.tvShows = tvShows;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeid_fk")
	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	@Column(name = "throwbackTVname")
	public String getThrowbackTvname() {
		return this.throwbackTvname;
	}

	public void setThrowbackTvname(String throwbackTvname) {
		this.throwbackTvname = throwbackTvname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "throwback")
	public Set<Throwbacktvdetail> getThrowbacktvdetails() {
		return this.throwbacktvdetails;
	}

	public void setThrowbacktvdetails(Set<Throwbacktvdetail> throwbacktvdetails) {
		this.throwbacktvdetails = throwbacktvdetails;
	}

}
