// default package
// Generated Nov 26, 2019 1:29:33 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TvShows generated by hbm2java
 */
@Entity
@Table(name = "tv_shows", catalog = "amazoneprime")
public class TvShows implements java.io.Serializable {

	private int tvshowid;
	private User user;
	private String tvshowname;
	private Set<Actionadventure> actionadventures = new HashSet<Actionadventure>(0);
	private Set<Throwback> throwbacks = new HashSet<Throwback>(0);
	private Set<Treanding> treandings = new HashSet<Treanding>(0);

	public TvShows() {
	}

	public TvShows(int tvshowid) {
		this.tvshowid = tvshowid;
	}

	public TvShows(int tvshowid, User user, String tvshowname, Set<Actionadventure> actionadventures,
			Set<Throwback> throwbacks, Set<Treanding> treandings) {
		this.tvshowid = tvshowid;
		this.user = user;
		this.tvshowname = tvshowname;
		this.actionadventures = actionadventures;
		this.throwbacks = throwbacks;
		this.treandings = treandings;
	}

	@Id

	@Column(name = "tvshowid", unique = true, nullable = false)
	public int getTvshowid() {
		return this.tvshowid;
	}

	public void setTvshowid(int tvshowid) {
		this.tvshowid = tvshowid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid_fk")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "tvshowname")
	public String getTvshowname() {
		return this.tvshowname;
	}

	public void setTvshowname(String tvshowname) {
		this.tvshowname = tvshowname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tvShows")
	public Set<Actionadventure> getActionadventures() {
		return this.actionadventures;
	}

	public void setActionadventures(Set<Actionadventure> actionadventures) {
		this.actionadventures = actionadventures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tvShows")
	public Set<Throwback> getThrowbacks() {
		return this.throwbacks;
	}

	public void setThrowbacks(Set<Throwback> throwbacks) {
		this.throwbacks = throwbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tvShows")
	public Set<Treanding> getTreandings() {
		return this.treandings;
	}

	public void setTreandings(Set<Treanding> treandings) {
		this.treandings = treandings;
	}

}
