// default package
// Generated Nov 26, 2019 1:29:33 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Watchdetail generated by hbm2java
 */
@Entity
@Table(name = "watchdetail", catalog = "amazoneprime")
public class Watchdetail implements java.io.Serializable {

	private int watchlistid;
	private Youwatchlist youwatchlist;
	private String listname;

	public Watchdetail() {
	}

	public Watchdetail(int watchlistid) {
		this.watchlistid = watchlistid;
	}

	public Watchdetail(int watchlistid, Youwatchlist youwatchlist, String listname) {
		this.watchlistid = watchlistid;
		this.youwatchlist = youwatchlist;
		this.listname = listname;
	}

	@Id

	@Column(name = "watchlistid", unique = true, nullable = false)
	public int getWatchlistid() {
		return this.watchlistid;
	}

	public void setWatchlistid(int watchlistid) {
		this.watchlistid = watchlistid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "watchlistid_fk")
	public Youwatchlist getYouwatchlist() {
		return this.youwatchlist;
	}

	public void setYouwatchlist(Youwatchlist youwatchlist) {
		this.youwatchlist = youwatchlist;
	}

	@Column(name = "listname")
	public String getListname() {
		return this.listname;
	}

	public void setListname(String listname) {
		this.listname = listname;
	}

}
