package fhfh;
// Generated Nov 26, 2019 3:59:58 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Primevideopin generated by hbm2java
 */
public class Primevideopin implements java.io.Serializable {

	private int primevideopinid;
	private Parentalcontrol parentalcontrol;
	private String primevideopinname;

	public Primevideopin() {
	}

	public Primevideopin(int primevideopinid) {
		this.primevideopinid = primevideopinid;
	}

	public Primevideopin(int primevideopinid, Parentalcontrol parentalcontrol, String primevideopinname) {
		this.primevideopinid = primevideopinid;
		this.parentalcontrol = parentalcontrol;
		this.primevideopinname = primevideopinname;
	}

	public int getPrimevideopinid() {
		return this.primevideopinid;
	}

	public void setPrimevideopinid(int primevideopinid) {
		this.primevideopinid = primevideopinid;
	}

	public Parentalcontrol getParentalcontrol() {
		return this.parentalcontrol;
	}

	public void setParentalcontrol(Parentalcontrol parentalcontrol) {
		this.parentalcontrol = parentalcontrol;
	}

	public String getPrimevideopinname() {
		return this.primevideopinname;
	}

	public void setPrimevideopinname(String primevideopinname) {
		this.primevideopinname = primevideopinname;
	}

}
