// default package
// Generated Nov 26, 2019 1:35:49 PM by Hibernate Tools 4.0.1.Final

/**
 * Accountsetting1 generated by hbm2java
 */
public class Accountsetting1 implements java.io.Serializable {

	private int accountsettingid;
	private User user;
	private String accountSettingname;

	public Accountsetting1() {
	}

	public Accountsetting1(int accountsettingid) {
		this.accountsettingid = accountsettingid;
	}

	public Accountsetting1(int accountsettingid, User user, String accountSettingname) {
		this.accountsettingid = accountsettingid;
		this.user = user;
		this.accountSettingname = accountSettingname;
	}

	public int getAccountsettingid() {
		return this.accountsettingid;
	}

	public void setAccountsettingid(int accountsettingid) {
		this.accountsettingid = accountsettingid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAccountSettingname() {
		return this.accountSettingname;
	}

	public void setAccountSettingname(String accountSettingname) {
		this.accountSettingname = accountSettingname;
	}

}
