// default package
// Generated Nov 26, 2019 1:35:49 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Accountsetting generated by hbm2java
 */
public class Accountsetting implements java.io.Serializable {

	private int accountsettingid;
	private User user;
	private String accountSettingname;
	private Set<Watchhistory> watchhistories = new HashSet<Watchhistory>(0);
	private Set<Youdevice> youdevices = new HashSet<Youdevice>(0);
	private Set<Parentalcontrol> parentalcontrols = new HashSet<Parentalcontrol>(0);
	private Set<Language> languages = new HashSet<Language>(0);
	private Set<Subtitle> subtitles = new HashSet<Subtitle>(0);
	private Set<Playback> playbacks = new HashSet<Playback>(0);
	private Set<Youaccount> youaccounts = new HashSet<Youaccount>(0);

	public Accountsetting() {
	}

	public Accountsetting(int accountsettingid) {
		this.accountsettingid = accountsettingid;
	}

	public Accountsetting(int accountsettingid, User user, String accountSettingname, Set<Watchhistory> watchhistories,
			Set<Youdevice> youdevices, Set<Parentalcontrol> parentalcontrols, Set<Language> languages,
			Set<Subtitle> subtitles, Set<Playback> playbacks, Set<Youaccount> youaccounts) {
		this.accountsettingid = accountsettingid;
		this.user = user;
		this.accountSettingname = accountSettingname;
		this.watchhistories = watchhistories;
		this.youdevices = youdevices;
		this.parentalcontrols = parentalcontrols;
		this.languages = languages;
		this.subtitles = subtitles;
		this.playbacks = playbacks;
		this.youaccounts = youaccounts;
	}

	public int getAccountsettingid() {
		return this.accountsettingid;
	}

	public void setAccountsettingid(int accountsettingid) {
		this.accountsettingid = accountsettingid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAccountSettingname() {
		return this.accountSettingname;
	}

	public void setAccountSettingname(String accountSettingname) {
		this.accountSettingname = accountSettingname;
	}

	public Set<Watchhistory> getWatchhistories() {
		return this.watchhistories;
	}

	public void setWatchhistories(Set<Watchhistory> watchhistories) {
		this.watchhistories = watchhistories;
	}

	public Set<Youdevice> getYoudevices() {
		return this.youdevices;
	}

	public void setYoudevices(Set<Youdevice> youdevices) {
		this.youdevices = youdevices;
	}

	public Set<Parentalcontrol> getParentalcontrols() {
		return this.parentalcontrols;
	}

	public void setParentalcontrols(Set<Parentalcontrol> parentalcontrols) {
		this.parentalcontrols = parentalcontrols;
	}

	public Set<Language> getLanguages() {
		return this.languages;
	}

	public void setLanguages(Set<Language> languages) {
		this.languages = languages;
	}

	public Set<Subtitle> getSubtitles() {
		return this.subtitles;
	}

	public void setSubtitles(Set<Subtitle> subtitles) {
		this.subtitles = subtitles;
	}

	public Set<Playback> getPlaybacks() {
		return this.playbacks;
	}

	public void setPlaybacks(Set<Playback> playbacks) {
		this.playbacks = playbacks;
	}

	public Set<Youaccount> getYouaccounts() {
		return this.youaccounts;
	}

	public void setYouaccounts(Set<Youaccount> youaccounts) {
		this.youaccounts = youaccounts;
	}

}
