// default package
// Generated Nov 26, 2019 1:35:49 PM by Hibernate Tools 4.0.1.Final

/**
 * Helpdetail generated by hbm2java
 */
public class Helpdetail implements java.io.Serializable {

	private int helpdetailid;
	private Help help;
	private String helpdetailname;

	public Helpdetail() {
	}

	public Helpdetail(int helpdetailid) {
		this.helpdetailid = helpdetailid;
	}

	public Helpdetail(int helpdetailid, Help help, String helpdetailname) {
		this.helpdetailid = helpdetailid;
		this.help = help;
		this.helpdetailname = helpdetailname;
	}

	public int getHelpdetailid() {
		return this.helpdetailid;
	}

	public void setHelpdetailid(int helpdetailid) {
		this.helpdetailid = helpdetailid;
	}

	public Help getHelp() {
		return this.help;
	}

	public void setHelp(Help help) {
		this.help = help;
	}

	public String getHelpdetailname() {
		return this.helpdetailname;
	}

	public void setHelpdetailname(String helpdetailname) {
		this.helpdetailname = helpdetailname;
	}

}
