// default package
// Generated Nov 26, 2019 1:35:49 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Home generated by hbm2java
 */
public class Home implements java.io.Serializable {

	private int homeid;
	private User user;
	private String homename;
	private Set<KidsFamily> kidsFamilies = new HashSet<KidsFamily>(0);
	private Set<Dramamovie> dramamovies = new HashSet<Dramamovie>(0);
	private Set<Throwback> throwbacks = new HashSet<Throwback>(0);
	private Set<Actionadventure> actionadventures = new HashSet<Actionadventure>(0);
	private Set<Comedymovie> comedymovies = new HashSet<Comedymovie>(0);
	private Set<Aoks> aokses = new HashSet<Aoks>(0);
	private Set<Treanding> treandings = new HashSet<Treanding>(0);
	private Set<Thrillermovie> thrillermovies = new HashSet<Thrillermovie>(0);
	private Set<KidsFamilytv> kidsFamilytvs = new HashSet<KidsFamilytv>(0);

	public Home() {
	}

	public Home(int homeid) {
		this.homeid = homeid;
	}

	public Home(int homeid, User user, String homename, Set<KidsFamily> kidsFamilies, Set<Dramamovie> dramamovies,
			Set<Throwback> throwbacks, Set<Actionadventure> actionadventures, Set<Comedymovie> comedymovies,
			Set<Aoks> aokses, Set<Treanding> treandings, Set<Thrillermovie> thrillermovies,
			Set<KidsFamilytv> kidsFamilytvs) {
		this.homeid = homeid;
		this.user = user;
		this.homename = homename;
		this.kidsFamilies = kidsFamilies;
		this.dramamovies = dramamovies;
		this.throwbacks = throwbacks;
		this.actionadventures = actionadventures;
		this.comedymovies = comedymovies;
		this.aokses = aokses;
		this.treandings = treandings;
		this.thrillermovies = thrillermovies;
		this.kidsFamilytvs = kidsFamilytvs;
	}

	public int getHomeid() {
		return this.homeid;
	}

	public void setHomeid(int homeid) {
		this.homeid = homeid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getHomename() {
		return this.homename;
	}

	public void setHomename(String homename) {
		this.homename = homename;
	}

	public Set<KidsFamily> getKidsFamilies() {
		return this.kidsFamilies;
	}

	public void setKidsFamilies(Set<KidsFamily> kidsFamilies) {
		this.kidsFamilies = kidsFamilies;
	}

	public Set<Dramamovie> getDramamovies() {
		return this.dramamovies;
	}

	public void setDramamovies(Set<Dramamovie> dramamovies) {
		this.dramamovies = dramamovies;
	}

	public Set<Throwback> getThrowbacks() {
		return this.throwbacks;
	}

	public void setThrowbacks(Set<Throwback> throwbacks) {
		this.throwbacks = throwbacks;
	}

	public Set<Actionadventure> getActionadventures() {
		return this.actionadventures;
	}

	public void setActionadventures(Set<Actionadventure> actionadventures) {
		this.actionadventures = actionadventures;
	}

	public Set<Comedymovie> getComedymovies() {
		return this.comedymovies;
	}

	public void setComedymovies(Set<Comedymovie> comedymovies) {
		this.comedymovies = comedymovies;
	}

	public Set<Aoks> getAokses() {
		return this.aokses;
	}

	public void setAokses(Set<Aoks> aokses) {
		this.aokses = aokses;
	}

	public Set<Treanding> getTreandings() {
		return this.treandings;
	}

	public void setTreandings(Set<Treanding> treandings) {
		this.treandings = treandings;
	}

	public Set<Thrillermovie> getThrillermovies() {
		return this.thrillermovies;
	}

	public void setThrillermovies(Set<Thrillermovie> thrillermovies) {
		this.thrillermovies = thrillermovies;
	}

	public Set<KidsFamilytv> getKidsFamilytvs() {
		return this.kidsFamilytvs;
	}

	public void setKidsFamilytvs(Set<KidsFamilytv> kidsFamilytvs) {
		this.kidsFamilytvs = kidsFamilytvs;
	}

}
