// default package
// Generated Nov 26, 2019 1:35:49 PM by Hibernate Tools 4.0.1.Final

/**
 * Kidsfamilymoviedetail generated by hbm2java
 */
public class Kidsfamilymoviedetail implements java.io.Serializable {

	private int kidsFamilyMovieDetailid;
	private KidsFamily kidsFamily;
	private String kidsFamilyMovieDetailname;

	public Kidsfamilymoviedetail() {
	}

	public Kidsfamilymoviedetail(int kidsFamilyMovieDetailid) {
		this.kidsFamilyMovieDetailid = kidsFamilyMovieDetailid;
	}

	public Kidsfamilymoviedetail(int kidsFamilyMovieDetailid, KidsFamily kidsFamily, String kidsFamilyMovieDetailname) {
		this.kidsFamilyMovieDetailid = kidsFamilyMovieDetailid;
		this.kidsFamily = kidsFamily;
		this.kidsFamilyMovieDetailname = kidsFamilyMovieDetailname;
	}

	public int getKidsFamilyMovieDetailid() {
		return this.kidsFamilyMovieDetailid;
	}

	public void setKidsFamilyMovieDetailid(int kidsFamilyMovieDetailid) {
		this.kidsFamilyMovieDetailid = kidsFamilyMovieDetailid;
	}

	public KidsFamily getKidsFamily() {
		return this.kidsFamily;
	}

	public void setKidsFamily(KidsFamily kidsFamily) {
		this.kidsFamily = kidsFamily;
	}

	public String getKidsFamilyMovieDetailname() {
		return this.kidsFamilyMovieDetailname;
	}

	public void setKidsFamilyMovieDetailname(String kidsFamilyMovieDetailname) {
		this.kidsFamilyMovieDetailname = kidsFamilyMovieDetailname;
	}

}
