// default package
// Generated Nov 26, 2019 1:35:49 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private int languageid;
	private Accountsetting accountsetting;
	private String languragename;
	private Set<Weblanguage> weblanguages = new HashSet<Weblanguage>(0);

	public Language() {
	}

	public Language(int languageid) {
		this.languageid = languageid;
	}

	public Language(int languageid, Accountsetting accountsetting, String languragename,
			Set<Weblanguage> weblanguages) {
		this.languageid = languageid;
		this.accountsetting = accountsetting;
		this.languragename = languragename;
		this.weblanguages = weblanguages;
	}

	public int getLanguageid() {
		return this.languageid;
	}

	public void setLanguageid(int languageid) {
		this.languageid = languageid;
	}

	public Accountsetting getAccountsetting() {
		return this.accountsetting;
	}

	public void setAccountsetting(Accountsetting accountsetting) {
		this.accountsetting = accountsetting;
	}

	public String getLanguragename() {
		return this.languragename;
	}

	public void setLanguragename(String languragename) {
		this.languragename = languragename;
	}

	public Set<Weblanguage> getWeblanguages() {
		return this.weblanguages;
	}

	public void setWeblanguages(Set<Weblanguage> weblanguages) {
		this.weblanguages = weblanguages;
	}

}
