// default package
// Generated Nov 26, 2019 1:35:49 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TvShows generated by hbm2java
 */
public class TvShows implements java.io.Serializable {

	private int tvshowid;
	private User user;
	private String tvshowname;
	private Set<Actionadventure> actionadventures = new HashSet<Actionadventure>(0);
	private Set<Throwback> throwbacks = new HashSet<Throwback>(0);
	private Set<Treanding> treandings = new HashSet<Treanding>(0);

	public TvShows() {
	}

	public TvShows(int tvshowid) {
		this.tvshowid = tvshowid;
	}

	public TvShows(int tvshowid, User user, String tvshowname, Set<Actionadventure> actionadventures,
			Set<Throwback> throwbacks, Set<Treanding> treandings) {
		this.tvshowid = tvshowid;
		this.user = user;
		this.tvshowname = tvshowname;
		this.actionadventures = actionadventures;
		this.throwbacks = throwbacks;
		this.treandings = treandings;
	}

	public int getTvshowid() {
		return this.tvshowid;
	}

	public void setTvshowid(int tvshowid) {
		this.tvshowid = tvshowid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTvshowname() {
		return this.tvshowname;
	}

	public void setTvshowname(String tvshowname) {
		this.tvshowname = tvshowname;
	}

	public Set<Actionadventure> getActionadventures() {
		return this.actionadventures;
	}

	public void setActionadventures(Set<Actionadventure> actionadventures) {
		this.actionadventures = actionadventures;
	}

	public Set<Throwback> getThrowbacks() {
		return this.throwbacks;
	}

	public void setThrowbacks(Set<Throwback> throwbacks) {
		this.throwbacks = throwbacks;
	}

	public Set<Treanding> getTreandings() {
		return this.treandings;
	}

	public void setTreandings(Set<Treanding> treandings) {
		this.treandings = treandings;
	}

}
