package abhi;
// Generated Nov 26, 2019 4:53:06 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Treandingtvdetail generated by hbm2java
 */
public class Treandingtvdetail implements java.io.Serializable {

	private int treandingtvdetailid;
	private Treanding treanding;
	private String treandingtvdetailname;

	public Treandingtvdetail() {
	}

	public Treandingtvdetail(int treandingtvdetailid) {
		this.treandingtvdetailid = treandingtvdetailid;
	}

	public Treandingtvdetail(int treandingtvdetailid, Treanding treanding, String treandingtvdetailname) {
		this.treandingtvdetailid = treandingtvdetailid;
		this.treanding = treanding;
		this.treandingtvdetailname = treandingtvdetailname;
	}

	public int getTreandingtvdetailid() {
		return this.treandingtvdetailid;
	}

	public void setTreandingtvdetailid(int treandingtvdetailid) {
		this.treandingtvdetailid = treandingtvdetailid;
	}

	public Treanding getTreanding() {
		return this.treanding;
	}

	public void setTreanding(Treanding treanding) {
		this.treanding = treanding;
	}

	public String getTreandingtvdetailname() {
		return this.treandingtvdetailname;
	}

	public void setTreandingtvdetailname(String treandingtvdetailname) {
		this.treandingtvdetailname = treandingtvdetailname;
	}

}
