package deepak;
// Generated Nov 26, 2019 4:44:51 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Parentalcontrol generated by hbm2java
 */
public class Parentalcontrol implements java.io.Serializable {

	private int parentalid;
	private Accountsetting accountsetting;
	private String parentalname;
	private Set primevideopins = new HashSet(0);

	public Parentalcontrol() {
	}

	public Parentalcontrol(int parentalid) {
		this.parentalid = parentalid;
	}

	public Parentalcontrol(int parentalid, Accountsetting accountsetting, String parentalname, Set primevideopins) {
		this.parentalid = parentalid;
		this.accountsetting = accountsetting;
		this.parentalname = parentalname;
		this.primevideopins = primevideopins;
	}

	public int getParentalid() {
		return this.parentalid;
	}

	public void setParentalid(int parentalid) {
		this.parentalid = parentalid;
	}

	public Accountsetting getAccountsetting() {
		return this.accountsetting;
	}

	public void setAccountsetting(Accountsetting accountsetting) {
		this.accountsetting = accountsetting;
	}

	public String getParentalname() {
		return this.parentalname;
	}

	public void setParentalname(String parentalname) {
		this.parentalname = parentalname;
	}

	public Set getPrimevideopins() {
		return this.primevideopins;
	}

	public void setPrimevideopins(Set primevideopins) {
		this.primevideopins = primevideopins;
	}

}
