package hhh;
// Generated Nov 26, 2019 4:14:27 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Signout generated by hbm2java
 */
public class Signout implements java.io.Serializable {

	private int signoutid;
	private User user;
	private String signoutname;

	public Signout() {
	}

	public Signout(int signoutid) {
		this.signoutid = signoutid;
	}

	public Signout(int signoutid, User user, String signoutname) {
		this.signoutid = signoutid;
		this.user = user;
		this.signoutname = signoutname;
	}

	public int getSignoutid() {
		return this.signoutid;
	}

	public void setSignoutid(int signoutid) {
		this.signoutid = signoutid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getSignoutname() {
		return this.signoutname;
	}

	public void setSignoutname(String signoutname) {
		this.signoutname = signoutname;
	}

}
