package com;
// Generated Nov 26, 2019 2:52:51 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Kids generated by hbm2java
 */
public class Kids implements java.io.Serializable {

	private int kidsid;
	private User user;
	private String kidsname;
	private Set kidsFamilies = new HashSet(0);
	private Set kidsFamilytvs = new HashSet(0);
	private Set aokses = new HashSet(0);

	public Kids() {
	}

	public Kids(int kidsid) {
		this.kidsid = kidsid;
	}

	public Kids(int kidsid, User user, String kidsname, Set kidsFamilies, Set kidsFamilytvs, Set aokses) {
		this.kidsid = kidsid;
		this.user = user;
		this.kidsname = kidsname;
		this.kidsFamilies = kidsFamilies;
		this.kidsFamilytvs = kidsFamilytvs;
		this.aokses = aokses;
	}

	public int getKidsid() {
		return this.kidsid;
	}

	public void setKidsid(int kidsid) {
		this.kidsid = kidsid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getKidsname() {
		return this.kidsname;
	}

	public void setKidsname(String kidsname) {
		this.kidsname = kidsname;
	}

	public Set getKidsFamilies() {
		return this.kidsFamilies;
	}

	public void setKidsFamilies(Set kidsFamilies) {
		this.kidsFamilies = kidsFamilies;
	}

	public Set getKidsFamilytvs() {
		return this.kidsFamilytvs;
	}

	public void setKidsFamilytvs(Set kidsFamilytvs) {
		this.kidsFamilytvs = kidsFamilytvs;
	}

	public Set getAokses() {
		return this.aokses;
	}

	public void setAokses(Set aokses) {
		this.aokses = aokses;
	}

}
