package com;
// Generated Nov 26, 2019 2:52:51 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Throwback generated by hbm2java
 */
public class Throwback implements java.io.Serializable {

	private int throwbackTvid;
	private Home home;
	private TvShows tvShows;
	private String throwbackTvname;
	private Set throwbacktvdetails = new HashSet(0);

	public Throwback() {
	}

	public Throwback(int throwbackTvid) {
		this.throwbackTvid = throwbackTvid;
	}

	public Throwback(int throwbackTvid, Home home, TvShows tvShows, String throwbackTvname, Set throwbacktvdetails) {
		this.throwbackTvid = throwbackTvid;
		this.home = home;
		this.tvShows = tvShows;
		this.throwbackTvname = throwbackTvname;
		this.throwbacktvdetails = throwbacktvdetails;
	}

	public int getThrowbackTvid() {
		return this.throwbackTvid;
	}

	public void setThrowbackTvid(int throwbackTvid) {
		this.throwbackTvid = throwbackTvid;
	}

	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	public TvShows getTvShows() {
		return this.tvShows;
	}

	public void setTvShows(TvShows tvShows) {
		this.tvShows = tvShows;
	}

	public String getThrowbackTvname() {
		return this.throwbackTvname;
	}

	public void setThrowbackTvname(String throwbackTvname) {
		this.throwbackTvname = throwbackTvname;
	}

	public Set getThrowbacktvdetails() {
		return this.throwbacktvdetails;
	}

	public void setThrowbacktvdetails(Set throwbacktvdetails) {
		this.throwbacktvdetails = throwbacktvdetails;
	}

}
