package com;
// Generated Nov 26, 2019 2:52:51 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Youdevice generated by hbm2java
 */
public class Youdevice implements java.io.Serializable {

	private int yourdeviceid;
	private Accountsetting accountsetting;
	private String yourdecicename;
	private Set registerdevices = new HashSet(0);

	public Youdevice() {
	}

	public Youdevice(int yourdeviceid) {
		this.yourdeviceid = yourdeviceid;
	}

	public Youdevice(int yourdeviceid, Accountsetting accountsetting, String yourdecicename, Set registerdevices) {
		this.yourdeviceid = yourdeviceid;
		this.accountsetting = accountsetting;
		this.yourdecicename = yourdecicename;
		this.registerdevices = registerdevices;
	}

	public int getYourdeviceid() {
		return this.yourdeviceid;
	}

	public void setYourdeviceid(int yourdeviceid) {
		this.yourdeviceid = yourdeviceid;
	}

	public Accountsetting getAccountsetting() {
		return this.accountsetting;
	}

	public void setAccountsetting(Accountsetting accountsetting) {
		this.accountsetting = accountsetting;
	}

	public String getYourdecicename() {
		return this.yourdecicename;
	}

	public void setYourdecicename(String yourdecicename) {
		this.yourdecicename = yourdecicename;
	}

	public Set getRegisterdevices() {
		return this.registerdevices;
	}

	public void setRegisterdevices(Set registerdevices) {
		this.registerdevices = registerdevices;
	}

}
