package dbb;
// Generated Nov 26, 2019 4:03:20 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Treanding generated by hbm2java
 */
public class Treanding implements java.io.Serializable {

	private int treandingtvid;
	private Home home;
	private TvShows tvShows;
	private String treandingtvname;
	private Set treandingtvdetails = new HashSet(0);

	public Treanding() {
	}

	public Treanding(int treandingtvid) {
		this.treandingtvid = treandingtvid;
	}

	public Treanding(int treandingtvid, Home home, TvShows tvShows, String treandingtvname, Set treandingtvdetails) {
		this.treandingtvid = treandingtvid;
		this.home = home;
		this.tvShows = tvShows;
		this.treandingtvname = treandingtvname;
		this.treandingtvdetails = treandingtvdetails;
	}

	public int getTreandingtvid() {
		return this.treandingtvid;
	}

	public void setTreandingtvid(int treandingtvid) {
		this.treandingtvid = treandingtvid;
	}

	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	public TvShows getTvShows() {
		return this.tvShows;
	}

	public void setTvShows(TvShows tvShows) {
		this.tvShows = tvShows;
	}

	public String getTreandingtvname() {
		return this.treandingtvname;
	}

	public void setTreandingtvname(String treandingtvname) {
		this.treandingtvname = treandingtvname;
	}

	public Set getTreandingtvdetails() {
		return this.treandingtvdetails;
	}

	public void setTreandingtvdetails(Set treandingtvdetails) {
		this.treandingtvdetails = treandingtvdetails;
	}

}
