// default package
// Generated Nov 26, 2019 1:28:02 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * KidsFamily generated by hbm2java
 */
public class KidsFamily implements java.io.Serializable {

	private int kidsFamilyMovieid;
	private Kids kids;
	private Home home;
	private String kidsFamilyMoviename;
	private Set<Kidsfamilymoviedetail> kidsfamilymoviedetails = new HashSet<Kidsfamilymoviedetail>(0);

	public KidsFamily() {
	}

	public KidsFamily(int kidsFamilyMovieid) {
		this.kidsFamilyMovieid = kidsFamilyMovieid;
	}

	public KidsFamily(int kidsFamilyMovieid, Kids kids, Home home, String kidsFamilyMoviename,
			Set<Kidsfamilymoviedetail> kidsfamilymoviedetails) {
		this.kidsFamilyMovieid = kidsFamilyMovieid;
		this.kids = kids;
		this.home = home;
		this.kidsFamilyMoviename = kidsFamilyMoviename;
		this.kidsfamilymoviedetails = kidsfamilymoviedetails;
	}

	public int getKidsFamilyMovieid() {
		return this.kidsFamilyMovieid;
	}

	public void setKidsFamilyMovieid(int kidsFamilyMovieid) {
		this.kidsFamilyMovieid = kidsFamilyMovieid;
	}

	public Kids getKids() {
		return this.kids;
	}

	public void setKids(Kids kids) {
		this.kids = kids;
	}

	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	public String getKidsFamilyMoviename() {
		return this.kidsFamilyMoviename;
	}

	public void setKidsFamilyMoviename(String kidsFamilyMoviename) {
		this.kidsFamilyMoviename = kidsFamilyMoviename;
	}

	public Set<Kidsfamilymoviedetail> getKidsfamilymoviedetails() {
		return this.kidsfamilymoviedetails;
	}

	public void setKidsfamilymoviedetails(Set<Kidsfamilymoviedetail> kidsfamilymoviedetails) {
		this.kidsfamilymoviedetails = kidsfamilymoviedetails;
	}

}
