// default package
// Generated Nov 26, 2019 1:28:02 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Subtitle generated by hbm2java
 */
public class Subtitle implements java.io.Serializable {

	private int subtitleid;
	private Accountsetting accountsetting;
	private String subtitlename;
	private Set<Subtitledetail> subtitledetails = new HashSet<Subtitledetail>(0);

	public Subtitle() {
	}

	public Subtitle(int subtitleid) {
		this.subtitleid = subtitleid;
	}

	public Subtitle(int subtitleid, Accountsetting accountsetting, String subtitlename,
			Set<Subtitledetail> subtitledetails) {
		this.subtitleid = subtitleid;
		this.accountsetting = accountsetting;
		this.subtitlename = subtitlename;
		this.subtitledetails = subtitledetails;
	}

	public int getSubtitleid() {
		return this.subtitleid;
	}

	public void setSubtitleid(int subtitleid) {
		this.subtitleid = subtitleid;
	}

	public Accountsetting getAccountsetting() {
		return this.accountsetting;
	}

	public void setAccountsetting(Accountsetting accountsetting) {
		this.accountsetting = accountsetting;
	}

	public String getSubtitlename() {
		return this.subtitlename;
	}

	public void setSubtitlename(String subtitlename) {
		this.subtitlename = subtitlename;
	}

	public Set<Subtitledetail> getSubtitledetails() {
		return this.subtitledetails;
	}

	public void setSubtitledetails(Set<Subtitledetail> subtitledetails) {
		this.subtitledetails = subtitledetails;
	}

}
