// default package
// Generated Nov 26, 2019 1:28:02 PM by Hibernate Tools 4.0.1.Final

/**
 * Watchdetail generated by hbm2java
 */
public class Watchdetail implements java.io.Serializable {

	private int watchlistid;
	private Youwatchlist youwatchlist;
	private String listname;

	public Watchdetail() {
	}

	public Watchdetail(int watchlistid) {
		this.watchlistid = watchlistid;
	}

	public Watchdetail(int watchlistid, Youwatchlist youwatchlist, String listname) {
		this.watchlistid = watchlistid;
		this.youwatchlist = youwatchlist;
		this.listname = listname;
	}

	public int getWatchlistid() {
		return this.watchlistid;
	}

	public void setWatchlistid(int watchlistid) {
		this.watchlistid = watchlistid;
	}

	public Youwatchlist getYouwatchlist() {
		return this.youwatchlist;
	}

	public void setYouwatchlist(Youwatchlist youwatchlist) {
		this.youwatchlist = youwatchlist;
	}

	public String getListname() {
		return this.listname;
	}

	public void setListname(String listname) {
		this.listname = listname;
	}

}
