// default package
// Generated Nov 26, 2019 2:40:40 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Help generated by hbm2java
 */
public class Help implements java.io.Serializable {

	private int helpid;
	private User user;
	private String helpname;
	private Set helpdetails = new HashSet(0);

	public Help() {
	}

	public Help(int helpid) {
		this.helpid = helpid;
	}

	public Help(int helpid, User user, String helpname, Set helpdetails) {
		this.helpid = helpid;
		this.user = user;
		this.helpname = helpname;
		this.helpdetails = helpdetails;
	}

	public int getHelpid() {
		return this.helpid;
	}

	public void setHelpid(int helpid) {
		this.helpid = helpid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getHelpname() {
		return this.helpname;
	}

	public void setHelpname(String helpname) {
		this.helpname = helpname;
	}

	public Set getHelpdetails() {
		return this.helpdetails;
	}

	public void setHelpdetails(Set helpdetails) {
		this.helpdetails = helpdetails;
	}

}
