package deep;
// Generated Nov 26, 2019 3:55:57 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Movie generated by hbm2java
 */
public class Movie implements java.io.Serializable {

	private int moviesid;
	private User user;
	private String moviesname;
	private Set thrillermovies = new HashSet(0);
	private Set dramamovies = new HashSet(0);
	private Set comedymovies = new HashSet(0);

	public Movie() {
	}

	public Movie(int moviesid) {
		this.moviesid = moviesid;
	}

	public Movie(int moviesid, User user, String moviesname, Set thrillermovies, Set dramamovies, Set comedymovies) {
		this.moviesid = moviesid;
		this.user = user;
		this.moviesname = moviesname;
		this.thrillermovies = thrillermovies;
		this.dramamovies = dramamovies;
		this.comedymovies = comedymovies;
	}

	public int getMoviesid() {
		return this.moviesid;
	}

	public void setMoviesid(int moviesid) {
		this.moviesid = moviesid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getMoviesname() {
		return this.moviesname;
	}

	public void setMoviesname(String moviesname) {
		this.moviesname = moviesname;
	}

	public Set getThrillermovies() {
		return this.thrillermovies;
	}

	public void setThrillermovies(Set thrillermovies) {
		this.thrillermovies = thrillermovies;
	}

	public Set getDramamovies() {
		return this.dramamovies;
	}

	public void setDramamovies(Set dramamovies) {
		this.dramamovies = dramamovies;
	}

	public Set getComedymovies() {
		return this.comedymovies;
	}

	public void setComedymovies(Set comedymovies) {
		this.comedymovies = comedymovies;
	}

}
