// default package
// Generated Nov 26, 2019 1:40:31 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Accountsetting1 generated by hbm2java
 */
@Entity
@Table(name = "accountsetting1", catalog = "amazoneprime")
public class Accountsetting1 implements java.io.Serializable {

	private int accountsettingid;
	private User user;
	private String accountSettingname;

	public Accountsetting1() {
	}

	public Accountsetting1(int accountsettingid) {
		this.accountsettingid = accountsettingid;
	}

	public Accountsetting1(int accountsettingid, User user, String accountSettingname) {
		this.accountsettingid = accountsettingid;
		this.user = user;
		this.accountSettingname = accountSettingname;
	}

	@Id

	@Column(name = "accountsettingid", unique = true, nullable = false)
	public int getAccountsettingid() {
		return this.accountsettingid;
	}

	public void setAccountsettingid(int accountsettingid) {
		this.accountsettingid = accountsettingid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid_fk")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "accountSettingname")
	public String getAccountSettingname() {
		return this.accountSettingname;
	}

	public void setAccountSettingname(String accountSettingname) {
		this.accountSettingname = accountSettingname;
	}

}
