// default package
// Generated Nov 26, 2019 1:40:31 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Signout generated by hbm2java
 */
@Entity
@Table(name = "signout", catalog = "amazoneprime")
public class Signout implements java.io.Serializable {

	private int signoutid;
	private User user;
	private String signoutname;

	public Signout() {
	}

	public Signout(int signoutid) {
		this.signoutid = signoutid;
	}

	public Signout(int signoutid, User user, String signoutname) {
		this.signoutid = signoutid;
		this.user = user;
		this.signoutname = signoutname;
	}

	@Id

	@Column(name = "signoutid", unique = true, nullable = false)
	public int getSignoutid() {
		return this.signoutid;
	}

	public void setSignoutid(int signoutid) {
		this.signoutid = signoutid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid_fk")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "signoutname")
	public String getSignoutname() {
		return this.signoutname;
	}

	public void setSignoutname(String signoutname) {
		this.signoutname = signoutname;
	}

}
