// default package
// Generated Nov 26, 2019 1:40:31 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Treandingtvdetail generated by hbm2java
 */
@Entity
@Table(name = "treandingtvdetail", catalog = "amazoneprime")
public class Treandingtvdetail implements java.io.Serializable {

	private int treandingtvdetailid;
	private Treanding treanding;
	private String treandingtvdetailname;

	public Treandingtvdetail() {
	}

	public Treandingtvdetail(int treandingtvdetailid) {
		this.treandingtvdetailid = treandingtvdetailid;
	}

	public Treandingtvdetail(int treandingtvdetailid, Treanding treanding, String treandingtvdetailname) {
		this.treandingtvdetailid = treandingtvdetailid;
		this.treanding = treanding;
		this.treandingtvdetailname = treandingtvdetailname;
	}

	@Id

	@Column(name = "treandingtvdetailid", unique = true, nullable = false)
	public int getTreandingtvdetailid() {
		return this.treandingtvdetailid;
	}

	public void setTreandingtvdetailid(int treandingtvdetailid) {
		this.treandingtvdetailid = treandingtvdetailid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "treandingtvid_fk")
	public Treanding getTreanding() {
		return this.treanding;
	}

	public void setTreanding(Treanding treanding) {
		this.treanding = treanding;
	}

	@Column(name = "treandingtvdetailname")
	public String getTreandingtvdetailname() {
		return this.treandingtvdetailname;
	}

	public void setTreandingtvdetailname(String treandingtvdetailname) {
		this.treandingtvdetailname = treandingtvdetailname;
	}

}
