// default package
// Generated Nov 26, 2019 1:40:31 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Watchanywheredetail generated by hbm2java
 */
@Entity
@Table(name = "watchanywheredetail", catalog = "amazoneprime")
public class Watchanywheredetail implements java.io.Serializable {

	private int watchanywheredetailid;
	private Watchanywhere watchanywhere;
	private String watchanywheredetailname;

	public Watchanywheredetail() {
	}

	public Watchanywheredetail(int watchanywheredetailid) {
		this.watchanywheredetailid = watchanywheredetailid;
	}

	public Watchanywheredetail(int watchanywheredetailid, Watchanywhere watchanywhere, String watchanywheredetailname) {
		this.watchanywheredetailid = watchanywheredetailid;
		this.watchanywhere = watchanywhere;
		this.watchanywheredetailname = watchanywheredetailname;
	}

	@Id

	@Column(name = "watchanywheredetailid", unique = true, nullable = false)
	public int getWatchanywheredetailid() {
		return this.watchanywheredetailid;
	}

	public void setWatchanywheredetailid(int watchanywheredetailid) {
		this.watchanywheredetailid = watchanywheredetailid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "watchanywhereid_fk")
	public Watchanywhere getWatchanywhere() {
		return this.watchanywhere;
	}

	public void setWatchanywhere(Watchanywhere watchanywhere) {
		this.watchanywhere = watchanywhere;
	}

	@Column(name = "watchanywheredetailname")
	public String getWatchanywheredetailname() {
		return this.watchanywheredetailname;
	}

	public void setWatchanywheredetailname(String watchanywheredetailname) {
		this.watchanywheredetailname = watchanywheredetailname;
	}

}
