// default package
// Generated Nov 26, 2019 1:40:31 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Youdetail generated by hbm2java
 */
@Entity
@Table(name = "youdetail", catalog = "amazoneprime")
public class Youdetail implements java.io.Serializable {

	private int yourdetailid;
	private Youaccount youaccount;
	private String yourdetailname;

	public Youdetail() {
	}

	public Youdetail(int yourdetailid) {
		this.yourdetailid = yourdetailid;
	}

	public Youdetail(int yourdetailid, Youaccount youaccount, String yourdetailname) {
		this.yourdetailid = yourdetailid;
		this.youaccount = youaccount;
		this.yourdetailname = yourdetailname;
	}

	@Id

	@Column(name = "yourdetailid", unique = true, nullable = false)
	public int getYourdetailid() {
		return this.yourdetailid;
	}

	public void setYourdetailid(int yourdetailid) {
		this.yourdetailid = yourdetailid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "youaccount_fk")
	public Youaccount getYouaccount() {
		return this.youaccount;
	}

	public void setYouaccount(Youaccount youaccount) {
		this.youaccount = youaccount;
	}

	@Column(name = "yourdetailname")
	public String getYourdetailname() {
		return this.yourdetailname;
	}

	public void setYourdetailname(String yourdetailname) {
		this.yourdetailname = yourdetailname;
	}

}
