package rajesh;
// Generated Nov 26, 2019 4:36:19 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * KidsFamilytv generated by hbm2java
 */
public class KidsFamilytv implements java.io.Serializable {

	private int kidsFamilytvid;
	private Home home;
	private Kids kids;
	private String kidsFamilytvname;
	private Set kidsFamilytvdetails = new HashSet(0);

	public KidsFamilytv() {
	}

	public KidsFamilytv(int kidsFamilytvid) {
		this.kidsFamilytvid = kidsFamilytvid;
	}

	public KidsFamilytv(int kidsFamilytvid, Home home, Kids kids, String kidsFamilytvname, Set kidsFamilytvdetails) {
		this.kidsFamilytvid = kidsFamilytvid;
		this.home = home;
		this.kids = kids;
		this.kidsFamilytvname = kidsFamilytvname;
		this.kidsFamilytvdetails = kidsFamilytvdetails;
	}

	public int getKidsFamilytvid() {
		return this.kidsFamilytvid;
	}

	public void setKidsFamilytvid(int kidsFamilytvid) {
		this.kidsFamilytvid = kidsFamilytvid;
	}

	public Home getHome() {
		return this.home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	public Kids getKids() {
		return this.kids;
	}

	public void setKids(Kids kids) {
		this.kids = kids;
	}

	public String getKidsFamilytvname() {
		return this.kidsFamilytvname;
	}

	public void setKidsFamilytvname(String kidsFamilytvname) {
		this.kidsFamilytvname = kidsFamilytvname;
	}

	public Set getKidsFamilytvdetails() {
		return this.kidsFamilytvdetails;
	}

	public void setKidsFamilytvdetails(Set kidsFamilytvdetails) {
		this.kidsFamilytvdetails = kidsFamilytvdetails;
	}

}
