package rajesh;
// Generated Nov 26, 2019 4:36:19 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Youpaymenthistory generated by hbm2java
 */
public class Youpaymenthistory implements java.io.Serializable {

	private int youpaymenthistoryid;
	private Youaccount youaccount;
	private String youpaymenthistoryname;

	public Youpaymenthistory() {
	}

	public Youpaymenthistory(int youpaymenthistoryid) {
		this.youpaymenthistoryid = youpaymenthistoryid;
	}

	public Youpaymenthistory(int youpaymenthistoryid, Youaccount youaccount, String youpaymenthistoryname) {
		this.youpaymenthistoryid = youpaymenthistoryid;
		this.youaccount = youaccount;
		this.youpaymenthistoryname = youpaymenthistoryname;
	}

	public int getYoupaymenthistoryid() {
		return this.youpaymenthistoryid;
	}

	public void setYoupaymenthistoryid(int youpaymenthistoryid) {
		this.youpaymenthistoryid = youpaymenthistoryid;
	}

	public Youaccount getYouaccount() {
		return this.youaccount;
	}

	public void setYouaccount(Youaccount youaccount) {
		this.youaccount = youaccount;
	}

	public String getYoupaymenthistoryname() {
		return this.youpaymenthistoryname;
	}

	public void setYoupaymenthistoryname(String youpaymenthistoryname) {
		this.youpaymenthistoryname = youpaymenthistoryname;
	}

}
